name: DevSecOps-Security-Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Python Security Scan (Bandit)
        run: |
          pip install bandit
          bandit -r . -f txt

      - name: Build Local Image for Scanning
        run: docker build -t my-app:${{ github.sha }} .

      - name: Container Vulnerability Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1' # This fails the pipeline if vulnerabilities are found
          severity: 'CRITICAL,HIGH'

      - name: Login to Docker Hub
        if: success() # Only runs if security scans pass
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        if: success()
        run: |
          docker tag my-app:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/secure-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/secure-app:latest