name: DevSecOps-Security-Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Python Security Scan (Bandit)
        run: |
          pip install bandit
          # Scans code and fails if it finds High/Medium issues
          bandit -r . -f txt

      - name: Build Local Image for Scanning
        run: docker build -t my-app:${{ github.sha }} .

      - name: Container Vulnerability Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-app:${{ github.sha }}'
          format: 'table'
          # We set exit-code to '1' so it FAILS the build if it finds CRITICALs
          exit-code: '1' 
          severity: 'CRITICAL'
          # We also want to see HIGHs in the logs, even if they don't stop the build
          ignore-unfixed: true

      - name: Login to Docker Hub
        if: success() # This ensures we only login if the security scans passed
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        if: success()
        run: |
          docker tag my-app:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/secure-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/secure-app:latest